apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: elfraidi/api-gateway-service-nutrisport:latest
        ports:
        - containerPort: 8888
        env:
        - name: eurekaIp
          value: "discovery-service.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
