apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-and-requests-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: offers-and-requests-management-service
  template:
    metadata:
      labels:
        app: offers-and-requests-management-service
    spec:
      containers:
      - name: offers-and-requests-management-service
        image: elfraidi/offers-and-requests-management-service-nutrisport:latest
        ports:
        - containerPort: 3100
        env:
        - name: eurekaIp
          value: "discovery-service.default.svc.cluster.local"
        - name: gatewayIp
          value: "api-gateway-service.default.svc.cluster.local"
        - name: PORT
          value: "3100"
        - name: hostIp
          value: "192.168.0.156"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "nutriSport"
        - name: KAFKA_BROKER
          value: "192.168.0.156:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: offers-and-requests-management-service
spec:
  selector:
    app: offers-and-requests-management-service
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: LoadBalancer
