apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: elfraidi/payment-service-nutrisport:latest
        ports:
        - containerPort: 3400
        env:
        - name: eurekaIp
          value: "discovery-service.default.svc.cluster.local"
        - name: PORT
          value: "3400"
        - name: hostIp
          value: "192.168.0.114"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "nutriSport"
        - name: KAFKA_BROKER
          value: "192.168.0.114:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 3400
  type: LoadBalancer
