apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: elfraidi/payment-service-nutrisport:latest
        ports:
        - containerPort: 3400
        env:
        - name: IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "3400"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 3400
  type: ClusterIP
